# Make sure you've installed raspi-config and enabled i2c!!

services:
  jukebox:
    container_name: jukebox
    image: ghcr.io/boc-the-git/piico-jukebox:latest
    environment:
      - TZ=Australia/Melbourne
      - WEBHOOK_URL=http://<your ip/hostname>:8123/api/webhook/nfc-tag-scanned-
    devices:
      - "/dev/i2c-1:/dev/i2c-1:rwm"
    restart: unless-stopped
